name: Deploy Genshin Guess Who

on:
  workflow_run:
    workflows:
      - ESLint/prettier Linting
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Optional: Sicherstellen, dass alte Container gestoppt werden
            docker compose -f ~/automated/ggw/docker-compose.yml down || true
            
            cd ~/automated/ggw/app
            git pull origin main
            docker build -t lenmp/genshinguesswho:latest .
            cd ..

            docker compose -f ~/automated/ggw/docker-compose.yml up -d --build
          EOF
