name: Deploy Genshin Guess Who

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Optional: Sicherstellen, dass alte Container gestoppt werden
          docker compose -f ~/automated/ggw/docker-compose.yml down || true
          
          cd ~/automated/ggw/app
          git pull origin main
          docker build -t sveltekit-skeleton:latest .
          cd ..

          docker compose -f ~/automated/ggw/docker-compose.yml up -d --build
        EOF
