name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install --save-dev
      - name: Run linting
        run: npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Optional: Sicherstellen, dass alte Container gestoppt werden
            docker compose -f ~/automated/ggw/docker-compose.yml down || true
            
            cd ~/automated/ggw/app
            git pull origin main
            docker build -t lenmp/genshinguesswho:latest .
            cd ..

            docker compose -f ~/automated/ggw/docker-compose.yml up -d --build
          EOF
